### ISSUE TITLE
there should be a terminal velocity for entities

### ISSUE THREAD

**Issue by benwaffle** [Flafla2/Remote2D-Engine#5]
you can see a lack of one if you open the default map, enable particles, run the map, and jump off the edge

**Comment by Flafla2** [comment]
There is one, see maxVelocity in ComponentPlayer

**Comment by Flafla2** [comment]
Oh wait, is that only implemented in the x axis?  Either way it's an easy implementation.

**Comment by Flafla2** [comment]
This issue is now irrelevant, closed
